# Generated by Django 4.1.2 on 2022-12-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_contact_user_alter_contact_id_alter_customers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='diagnosis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
